export enum ConfigErrorCode {
  MISSING_ENV = 'CONFIG_MISSING_ENV',
  INTERNAL_SERVER_ERROR = 'CONFIG_INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'CONFIG_BAD_REQUEST',
  UNAUTHORIZED = 'CONFIG_UNAUTHORIZED',
  FORBIDDEN = 'CONFIG_FORBIDDEN',
  NOT_FOUND = 'CONFIG_NOT_FOUND',
  CONFLICT = 'CONFIG_CONFLICT',
  TOO_MANY_REQUESTS = 'CONFIG_TOO_MANY_REQUESTS',
  UNPROCESSABLE_ENTITY = 'CONFIG_UNPROCESSABLE_ENTITY',
}
