-- Hiring Mega X — schema đăng bài (nhóm tuyển dụng, content xoay vòng)
-- An toàn chạy lại: IF NOT EXISTS / ON CONFLICT / DROP POLICY IF EXISTS.
-- Auth model: PIN cookie + Supabase anon key (không dùng Supabase Auth)
-- → RLS tắt trên post_template.
-- Không có bảng lịch sử đăng riêng (post_log) — trạng thái "đã đăng" chỉ
-- theo dõi qua last_posted_at trên recruitment_group / post_template.

-- 1) Cột bổ sung trên recruitment_group (giữ data cũ)
ALTER TABLE public.recruitment_group
  ADD COLUMN IF NOT EXISTS link TEXT,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS cooldown_minutes INTEGER NOT NULL DEFAULT 1440,
  ADD COLUMN IF NOT EXISTS last_posted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS note TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'recruitment_group_cooldown_check'
      AND conrelid = 'public.recruitment_group'::REGCLASS
  ) THEN
    ALTER TABLE public.recruitment_group
      ADD CONSTRAINT recruitment_group_cooldown_check
      CHECK (cooldown_minutes >= 0);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_recruitment_group_category_active
ON public.recruitment_group (category, is_active);

CREATE INDEX IF NOT EXISTS idx_recruitment_group_ready_to_post
ON public.recruitment_group (category, is_active, last_posted_at, cooldown_minutes);


-- 2) post_template (content xoay vòng)
CREATE TABLE IF NOT EXISTS public.post_template (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL
    CONSTRAINT post_template_category_check
    CHECK (
      category IN (
        'HR','SALES','ADS','CONTENT','EDITOR','DESIGNER',
        'SEO','IT','ACCOUNTANT','PANCAKE','OTHER'
      )
    ),
  content TEXT NOT NULL
    CONSTRAINT post_template_content_check
    CHECK (BTRIM(content) <> ''),
  image_url TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_posted_at TIMESTAMPTZ,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_post_template_rotation
ON public.post_template (category, is_active, last_posted_at);

ALTER TABLE public.post_template DISABLE ROW LEVEL SECURITY;


-- 3) Trigger updated_at
CREATE OR REPLACE FUNCTION public.set_posting_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_recruitment_group_updated_at ON public.recruitment_group;
CREATE TRIGGER trg_recruitment_group_updated_at
BEFORE UPDATE ON public.recruitment_group
FOR EACH ROW
EXECUTE FUNCTION public.set_posting_updated_at();

DROP TRIGGER IF EXISTS trg_post_template_updated_at ON public.post_template;
CREATE TRIGGER trg_post_template_updated_at
BEFORE UPDATE ON public.post_template
FOR EACH ROW
EXECUTE FUNCTION public.set_posting_updated_at();


-- 4) Bucket ảnh (public, max 10MB) — dùng cho Compose / Content upload
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'images',
  'images',
  TRUE,
  10485760,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO UPDATE SET
  public = TRUE,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "Public can view images" ON storage.objects;
CREATE POLICY "Public can view images"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'images');

DROP POLICY IF EXISTS "Authenticated users can view images" ON storage.objects;
CREATE POLICY "Authenticated users can view images"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'images');

DROP POLICY IF EXISTS "Authenticated users can upload images" ON storage.objects;
CREATE POLICY "Authenticated users can upload images"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'images');

DROP POLICY IF EXISTS "Authenticated users can update images" ON storage.objects;
CREATE POLICY "Authenticated users can update images"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'images')
WITH CHECK (bucket_id = 'images');

DROP POLICY IF EXISTS "Authenticated users can delete images" ON storage.objects;
CREATE POLICY "Authenticated users can delete images"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'images');
