-- Hiring Mega X — lịch sử đăng bài (n8n ghi về Supabase)
-- Mỗi dòng = 1 lần đăng vào 1 nhóm. run_id nhóm các dòng của cùng 1 lần bấm "Đăng bài".
-- An toàn chạy lại: IF NOT EXISTS.
-- Auth model: PIN cookie + anon key (không dùng Supabase Auth) → RLS tắt, giống post_template.

CREATE TABLE IF NOT EXISTS public.post_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL,
  category TEXT,
  page_id TEXT,
  group_id TEXT NOT NULL,
  -- NULL khi content nhập tay (không lấy từ post_template)
  template_id BIGINT REFERENCES public.post_template(id) ON DELETE SET NULL,
  content TEXT,
  image_url TEXT NOT NULL DEFAULT '',
  post_id TEXT,
  ok BOOLEAN NOT NULL DEFAULT FALSE,
  error TEXT,
  posted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_post_log_run ON public.post_log (run_id);
CREATE INDEX IF NOT EXISTS idx_post_log_group ON public.post_log (group_id, posted_at DESC);
CREATE INDEX IF NOT EXISTS idx_post_log_template ON public.post_log (template_id, posted_at DESC);

ALTER TABLE public.post_log DISABLE ROW LEVEL SECURITY;
